default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PSQL_USER'] %>
  password: <%= ENV['PSQL_PASS'] %>
  timeout: 5000

development:
  <<: *default
  database: shramble

test:
  <<: *default
  database: shramble_test

production:
  <<: *default
  database: db/production.sqlite3
