default: &default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
